### ISSUE TITLE
Error during install - gyp ERR! configure error 

### ISSUE THREAD

**Issue by JohnMcLear** [brianc/node-pg-native#10]
I'd like to use this instead of the pg package in ueberDB but this error is a blocker.

```
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
gyp: Call to 'pg_config --libdir' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/jose/v0.10.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 3.5.0-18-generic
gyp ERR! command "node" "/home/jose/v0.10.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jose/ueberDB/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.4
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! libpq@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.2.1 install script.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.5.0-18-generic
npm ERR! command "node" "/home/jose/v0.10.4/bin/npm" "install"
npm ERR! cwd /home/jose/ueberDB
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jose/ueberDB/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pasupulaphani** [comment]
Looks like I've to install postgresql (server) to install ```libpq-dev```. I don't want to install postgresql server on a container, as it has to only connect to server.

I tried installing on postgresql-client but no use. I'm using ubuntu:14.04 . Any suggestions?
