### ISSUE TITLE
Cryptic "Error: connection pointer is NULL" exception if connectSync fails

### ISSUE THREAD

**Issue by monsanto** [brianc/node-pg-native#13]
A bad connection with `connect` gives a nice error:
```
> client.connect("dbname=nststnoentsantseo", function(err) { console.log(err) })
[Error: FATAL:  database "nststnoentsantseo" does not exist
```

A bad connection with `connectSync` does not:
```
> client.connectSync("dbname=nststnoentsantseo")
Error: connection pointer is NULL

    at PQ.connectSync (/host-smogon/build/node_modules/pg-native/node_modules/libpq/index.js:27:11)
    at Client.connectSync (/host-smogon/build/node_modules/pg-native/index.js:43:11)
    at repl:1:9
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

Node 10.33, Postgres 9.4

**Comment by brianc** [comment]
@monsanto I put a fix in here for you - pushing a new version now: https://github.com/brianc/node-libpq/pull/9
