### ISSUE TITLE
Cannot install Node 0.10.36, CentOS 6.4 & 7

### ISSUE THREAD

**Issue by galambalazs** [brianc/node-pg-native#18]
Here is **npm-debug.log**: http://pastebin.com/QHrpRpnR

And here is my console output:

````
> libpq@1.6.1 install /home/ec2-user/psql-test/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

make: Entering directory `/home/ec2-user/psql-test/node_modules/pg-native/node_modules/libpq/build'
  CXX(target) Release/obj.target/addon/src/connection.o
In file included from ../src/connection.cc:1:0:
../src/addon.h:6:22: fatal error: libpq-fe.h: No such file or directory
 #include <libpq-fe.h>
                      ^
compilation terminated.
make: *** [Release/obj.target/addon/src/connection.o] Error 1
make: Leaving directory `/home/ec2-user/psql-test/node_modules/pg-native/node_modules/libpq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.35-28.38.amzn1.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/psql-test/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.14.35-28.38.amzn1.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "pg-native"
npm ERR! node v0.10.36
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.6.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/psql-test/npm-debug.log
```

**Comment by brianc** [comment]
You'll need to install postgres client headers.  Your system can't find `libpq-fe.h` - I'm not sure the exact install instructions for your flavor of linux but googling for "installing postgres client driver cent os" will probably turn up the righ tinfo.

**Comment by galambalazs** [comment]
Thanks. For the record it was in the postgresql-devel package.: 

    yum install postgresql-devel

http://stackoverflow.com/questions/6040583/cant-find-the-libpq-fe-h-header-when-trying-to-install-pg-gem

**Comment by brianc** [comment]
Perfecto! So glad you got it working!!
