### ISSUE TITLE
install error, Ubuntu

### ISSUE THREAD

**Issue by Wisemant** [brianc/node-pg-native#25]
`alias bash node=nodejs`   is not helpin'
____
```bash
$npm install pg-native --save
npm http GET https://registry.npmjs.org/pg-native
npm http 304 https://registry.npmjs.org/pg-native
npm http GET https://registry.npmjs.org/readable-stream/1.0.31
npm http GET https://registry.npmjs.org/libpq
npm http 304 https://registry.npmjs.org/readable-stream/1.0.31
npm http 304 https://registry.npmjs.org/libpq
npm http GET https://registry.npmjs.org/pg-types/1.6.0
npm http 304 https://registry.npmjs.org/pg-types/1.6.0
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings/1.2.1

> libpq@1.6.4 install /media/Data1/domains/armoperator/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /media/Data1/domains/armoperator/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by brianc** [comment]
Can you try with version 1.9.0? I pushed a new version of libpq with expanded node version compatibility.

**Comment by Wisemant** [comment]
I'll do it in nearest spare time.
and problem has solution. It's  node-legacy     deb package.

**Comment by brianc** [comment]
Try with node v4.1 - everything should be working now!
