### ISSUE TITLE
Bindings: undefined symbol

### ISSUE THREAD

**Issue by pito-svk** [brianc/node-pg-native#40]
```
my@account:~/my/project$ node
> var pg = require('pg').native;
Error: /home/my/project/api/node_modules/libpq/build/Release/addon.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/my/project/api/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/my/project/api/node_modules/libpq/index.js:1:108)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by itamarwe** [comment]
I've also encountered this issue

**Comment by brianc** [comment]
you might want to try deleting and re-installing your `node_modules` folder

**Comment by itamarwe** [comment]
The problem was I was using coffee script, and while I updated my node.js, my global coffee-script installation kicked in.
To solve this, I ran:
```
npm update -g
```

**Comment by techsin** [comment]
deleting node_modules helped
