### ISSUE TITLE
Error: Cannot find module 'wkx'

### ISSUE THREAD

**Issue by nstuyvesant** [brianc/node-pg-native#60]
Node.js: 8.4.0
npm: 5.3.0
node-pg-native: 2.2.0
pg: 7.2.0
sequelize: 4.7.1

Tried to upgrade from 2.0.1 to 2.2.0 then deploy to Heroku and got the following error:
```
2017-08-24T12:10:40.580797+00:00 app[web.1]: Error: Cannot find module 'wkx'
2017-08-24T12:10:40.580798+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:489:15)
2017-08-24T12:10:40.580799+00:00 app[web.1]:     at Function.Module._load (module.js:439:25)
2017-08-24T12:10:40.580799+00:00 app[web.1]:     at Module.require (module.js:517:17)
2017-08-24T12:10:40.580800+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-08-24T12:10:40.580801+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/data-types.js:4:13)
2017-08-24T12:10:40.580801+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2017-08-24T12:10:40.580802+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2017-08-24T12:10:40.580803+00:00 app[web.1]:     at Module.load (module.js:507:32)
2017-08-24T12:10:40.580803+00:00 app[web.1]:     at tryModuleLoad (module.js:470:12)
2017-08-24T12:10:40.580804+00:00 app[web.1]:     at Function.Module._load (module.js:462:3)
2017-08-24T12:10:40.580804+00:00 app[web.1]:     at Module.require (module.js:517:17)
2017-08-24T12:10:40.580805+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-08-24T12:10:40.580806+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/sequelize/lib/data-types.js:842:22)
2017-08-24T12:10:40.580807+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2017-08-24T12:10:40.580807+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2017-08-24T12:10:40.580820+00:00 app[web.1]:     at Module.load (module.js:507:32)
```

Reverted back to 2.0.1 and all is well again. The problem might be upstream.

**Comment by brianc** [comment]
That is bizarre - the 2.2 build passed in CI - maybe has something to do with sequelize?

**Comment by nstuyvesant** [comment]
It really is bizarre. Could also be something odd going on with Heroku since I could run the project locally without errors.
