### ISSUE TITLE
Have node-gyp automatically select a compatible python version using the --python switch

### ISSUE THREAD

**Issue by dnjstrom** [brianc/node-pg-native#67]
On my system installing pg-native fails with an error because the default python version is python 3.

```fish
~/Desktop
❯ mkdir my-project

~/Desktop
❯ cd my-project/

~/Desktop/my-project
❯ yarn init -y
yarn init v1.5.1
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.03s.

~/Desktop/my-project
❯ yarn add pg-native^C

~/Desktop/my-project
❯ yarn add pg-native
yarn add v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠐ libpq: using node@8.10.0 | darwin | x64
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error An unexpected error occurred: "/Users/daniel/Desktop/my-project/node_modules/libpq: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/daniel/Desktop/my-project/node_modules/libpq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | darwin | x64
gyp ERR! configure error
gyp ERR! stack Error: Python executable \"/usr/local/bin/python\" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/daniel/Desktop/my-project/node_modules/libpq
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
```

As stated in the error message, I think it'd be nice if pg-native or node-libpq would pass the `--python` switch to node-gyp so it will automatically choose the correct python version if it exists:

> You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

For now though, one can manually configure yarn/npm to use python 2 by default and the installation will work:

```fish
~/Desktop/my-project
❯ which python2.7
/usr/bin/python2.7

~/Desktop/my-project
❯ yarn config set python /usr/bin/python2.7
yarn config v1.5.1
success Set "python" to "/usr/bin/python2.7".
✨  Done in 0.06s.

~/Desktop/my-project
❯ yarn add pg-native
yarn add v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 16 new dependencies.
info Direct dependencies
└─ pg-native@2.2.0
info All dependencies
├─ bindings@1.2.1
├─ core-util-is@1.0.2
├─ inherits@2.0.3
├─ isarray@0.0.1
├─ libpq@1.8.7
├─ nan@2.10.0
├─ pg-int8@1.0.1
├─ pg-native@2.2.0
├─ pg-types@1.13.0
├─ postgres-array@1.0.2
├─ postgres-bytea@1.0.0
├─ postgres-date@1.0.3
├─ postgres-interval@1.1.1
├─ readable-stream@1.0.31
├─ string_decoder@0.10.31
└─ xtend@4.0.1
✨  Done in 12.65s.

~/Desktop/my-project 13s
❯
```

**Comment by charmander** [comment]
> For now though, one can manually configure yarn/npm to use python 2 by default

That’s exactly how this should be handled, for all packages. pg-native isn’t in a good position to make guesses about your Python 2 installation.

**Comment by dnjstrom** [comment]
Oh, I was under the impression that the —python switch would auto-select the correct python version for you, but reviewing the documentation a bit closer I see you have to pass in the executable path - in which case I totally agree with you.

Closing the issue as solved. :)
